object_type: global_settings
overrides:
    "connection.pool.group.maxConnections": "1000"
    "connection.pool.user.maxConnections": "1000"
    "aggregates.create.joins.maximumKeyCardinality": "200000000"
    "tables.create.partitions.maximumEstimatedNumberOfPartitions": "1000000"
    "aggregates.creation.timeout": "8.hours"